apiVersion: v1
entries:
  vault:
  - apiVersion: v1
    created: "2020-01-08T06:35:32.0783315Z"
    description: Install and configure Vault on Kubernetes.
    digest: 43fb768ed9aab2416f78b7a70aaf142398159bb9e784d1de07fbc46368e26819
    home: https://www.vaultproject.io
    icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
    name: vault
    sources:
    - https://github.com/hashicorp/vault
    - https://github.com/hashicorp/vault-helm
    - https://github.com/hashicorp/vault-k8s
    urls:
    - https://raw.githubusercontent.com/theclinician/vault-helm/gh-pages/charts/vault-0.3.1.tgz
    version: 0.3.1
generated: "2020-01-08T06:35:32.0770689Z"
